# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 42161
  start_block: 0
  contracts:
  - name: L2ArbitrumGovernor
    address:
    - 0x789fC99093B09aD01C34DC7251D0C89ce743e5a4
    - 0xf07DeD9dC292157749B6Fd268E37DF6EA38395B9
    handler: src/EventHandlers.ts
    events:
    - event: Initialized(uint8 version)
    - event: LateQuorumVoteExtensionSet(uint64 oldVoteExtension, uint64 newVoteExtension)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: ProposalCanceled(uint256 proposalId)
    - event: ProposalCreated(uint256 proposalId, address proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 startBlock, uint256 endBlock, string description)
    - event: ProposalExecuted(uint256 proposalId)
    - event: ProposalExtended(uint256 indexed proposalId, uint64 extendedDeadline)
    - event: ProposalQueued(uint256 proposalId, uint256 eta)
    - event: ProposalThresholdSet(uint256 oldProposalThreshold, uint256 newProposalThreshold)
    - event: QuorumNumeratorUpdated(uint256 oldQuorumNumerator, uint256 newQuorumNumerator)
    - event: TimelockChange(address oldTimelock, address newTimelock)
    - event: VoteCast(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason)
    - event: VoteCastWithParams(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason, bytes params)
    - event: VotingDelaySet(uint256 oldVotingDelay, uint256 newVotingDelay)
    - event: VotingPeriodSet(uint256 oldVotingPeriod, uint256 newVotingPeriod)
rollback_on_reorg: false
